import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "How many European households are facing energy poverty?",
  "subtitle": "On average, 7.4% of households in the EU were unable to meet their energy needs in 2024. An improvement of 3.2% from 2023.",
  "colourSchemeClasses": 5,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,0.03900,FALSE,,,,,,,,,\nBelgium,BE,0.04900,FALSE,,,,,,,,,\nBulgaria,BG,0.1900,FALSE,,,,,,,,,\nCyprus,CY,0.14600,FALSE,,,,,,,,,\nCzechia,CZ,0.04900,FALSE,,,,,,,,,\nGermany,DE,0.06200,FALSE,,,,,,,,,\nDenmark,DK,0.04400,FALSE,,,,,,,,,\nEstonia,EE,0.03600,FALSE,,,,,,,,,\nGreece,EL,0.19200,FALSE,,,,,,,,,\nSpain,ES,0.17500,FALSE,,,,,,,,,\nFinland,FI,0.02700,FALSE,,,,,,,,,\nFrance,FR,0.12100,FALSE,,,,,,,,,\nCroatia,HR,0.06200,FALSE,,,,,,,,,\nHungary,HU,0.06100,FALSE,,,,,,,,,\nIreland,IE,0.07200,FALSE,,,,,,,,,\nItaly,IT,0.08600,FALSE,,,,,,,,,\nLithuania,LT,0.20000,FALSE,,,,,,,,,\nLuxembourg,LU,0.03600,FALSE,,,,,,,,,\nLatvia,LV,0.04900,FALSE,,,,,,,,,\nMalta,MT,0.06800,FALSE,,,,,,,,,\nNetherlands,NL,0.07100,FALSE,,,,,,,,,\nPoland,PL,0.04700,FALSE,,,,,,,,,\nPortugal,PT,0.20800,FALSE,,,,,,,,,\nRomania,RO,0.10800,FALSE,,,,,,,,,\nSweden,SE,0.04100,FALSE,,,,,,,,,\nSlovenia,SI,0.03300,FALSE,,,,,,,,,\nSlovakia,SK,0.08100,FALSE,,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.039,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.049,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.19,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.146,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.049,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.062,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.044,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.036,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.192,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.175,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.027,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.121,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.062,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.061,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.072,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.086,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.2,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.036,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.049,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.068,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.071,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.047,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.208,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.108,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.041,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.033,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.081,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "yellow-orange-red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": false,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurostat",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "Energy poverty occurs when a household must reduce its energy consumption to a degree that negatively impacts the inhabitants' health and wellbeing. Data for Austria, Ireland, Greece, France, Croatia, Lithuania, Malta, Portugal, Romania & Slovakia are from 2023.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://ec.europa.eu/eurostat/databrowser/view/ilc_mdes01/default/table?lang=en",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "of households",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How many European households are facing energy poverty?",
    "subtitle": "On average, 7.4% of households in the EU were unable to meet their energy needs in 2024. An improvement of 3.2% from 2023.",
    "textNoteDescription": "Note",
    "textNote": "Energy poverty occurs when a household must reduce its energy consumption to a degree that negatively impacts the inhabitants' health and wellbeing. Data for Austria, Ireland, Greece, France, Croatia, Lithuania, Malta, Portugal, Romania & Slovakia are from 2023.",
    "textSourceDescription": "Source",
    "textSource": "Eurostat",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here"
  },
  "clusters": [],
  "colorScale": null
});